import { Pipe, PipeTransform } from '@angular/core';

type AppLang = 'fr' | 'en' | 'ar';

const FALLBACK_LANG: AppLang = 'fr';

const TRANSLATIONS: Record<AppLang, Record<string, string>> = {
  fr: {
    'settings.title': 'Parametres',
    'settings.subtitle': 'Personnalisez votre experience QualiFlow et gerez vos preferences.',
    'settings.appearance': 'Apparence',
    'settings.darkMode': 'Mode sombre',
    'settings.darkModeDesc': 'Passer a une interface visuelle plus reposante pour vos yeux.',
    'settings.language': "Langue de l'interface",
    'settings.preferredLanguage': 'Langue preferee',
    'settings.preferredLanguageDesc': 'Determinez la langue utilisee pour les menus et les messages systemes.',
    'settings.selectLanguage': 'Selectionner une langue',
    'settings.about': 'Informations sur la plateforme',
    'settings.aboutText': "QualiFlow est une suite logicielle avancee dediee a la gestion de la qualite. Elle centralise le pilotage des processus, la maitrise documentaire et la gestion des non-conformites pour assurer une demarche d'amelioration continue optimale.",
    'settings.documentation': 'Documentation',
    'settings.support': 'Support technique',
    'sidebar.general': 'General',
    'sidebar.home': 'Accueil',
    'sidebar.notifications': 'Notifications',
    'sidebar.chatbot': 'Assistant GED',
    'sidebar.qualityManagement': 'Gestion qualite',
    'sidebar.processes': 'Processus',
    'sidebar.mapping': 'Cartographie',
    'sidebar.procedures': 'Procedures',
    'sidebar.nonConformities': 'Non-conformites',
    'sidebar.correctiveActions': 'Actions correctives',
    'sidebar.kpiIndicators': 'Indicateurs KPI',
    'sidebar.documents': 'Documents',
    'sidebar.departments': 'Departements',
    'sidebar.orgAdmin': 'Administration org',
    'sidebar.myOrganization': 'Mon organisation',
    'sidebar.usersRoles': 'Utilisateurs et roles',
    'sidebar.account': 'Compte',
    'sidebar.profile': 'Profil',
    'sidebar.settings': 'Parametres',
    'sidebar.organizations': 'Instituts / Organisations',
    'common.search': 'Recherche',
    'common.type': 'Type',
    'common.status': 'Statut',
    'common.severity': 'Severite',
    'common.filter': 'Filtrer',
    'common.reset': 'Reinitialiser',
    'common.code': 'Code',
    'common.title': 'Titre',
    'common.createdAt': 'Creation',
    'common.responsible': 'Responsable',
    'common.toDefine': 'A definir',
    'common.actions': 'Actions',
    'common.details': 'Details',
    'common.edit': 'Modifier',
    'common.delete': 'Supprimer',
    'common.refresh': 'Rafraichir',
    'common.allTypes': 'Tous les types',
    'common.allStatuses': 'Tous les statuts',
    'common.allSeverities': 'Toutes les severites',
    'list.processes.title': 'Processus',
    'list.processes.mapping': 'Cartographie',
    'list.processes.activeCount': 'processus actifs',
    'list.processes.new': 'Nouveau processus',
    'list.processes.searchPlaceholder': 'Code, nom ou description',
    'list.processes.pilot': 'Pilote',
    'list.processes.allPilots': 'Tous les pilotes',
    'list.processes.loading': 'Chargement des processus...',
    'list.processes.emptyTitle': 'Aucun processus trouve',
    'list.processes.emptyText': 'Ajuste les filtres ou cree un nouveau processus.',
    'list.processes.performance': 'Performance',
    'list.procedures.title': 'Procedures',
    'list.procedures.activeCount': 'procedures actives dans le referentiel',
    'list.procedures.new': 'Nouvelle procedure',
    'list.procedures.searchPlaceholder': 'Code, titre ou description',
    'list.procedures.allProcesses': 'Tous les processus',
    'list.procedures.allResponsibles': 'Tous les responsables',
    'list.procedures.loading': 'Chargement des procedures...',
    'list.procedures.emptyTitle': 'Aucune procedure trouvee',
    'list.procedures.emptyText': 'Ajuste les filtres ou cree une procedure.',
    'list.nonconformities.title': 'Non-conformites',
    'list.nonconformities.subtitle': 'Suivi des ecarts qualite et du traitement correctif',
    'list.nonconformities.new': 'Nouvelle fiche',
    'list.nonconformities.searchPlaceholder': 'Code, titre ou description',
    'list.nonconformities.totalManaged': 'Total gere',
    'list.nonconformities.records': 'Fiches enregistrees',
    'list.nonconformities.openInProgress': 'En cours / Ouvertes',
    'list.nonconformities.opened': 'ouvertes',
    'list.nonconformities.inProgress': 'en cours',
    'list.nonconformities.critical': 'Critiques',
    'list.nonconformities.criticalHelp': 'Action immediate requise',
    'list.nonconformities.overdueActions': 'Actions en retard',
    'list.nonconformities.deadlinesExceeded': 'Delais depasses',
    'list.nonconformities.loading': 'Analyse des donnees...',
    'list.nonconformities.emptyTitle': 'Aucune non-conformite',
    'list.nonconformities.emptyText': 'Ajuste les filtres ou cree une nouvelle fiche si necessaire.',
    'list.nonconformities.titleDesc': 'Titre & Description',
    'list.nonconformities.state': 'Etat',
    'list.nonconformities.linkedTo': 'Liaison',
    'list.nonconformities.detected': 'Detection',
    'list.indicators.title': 'Indicateurs KPI',
    'list.indicators.subtitle': 'Pilotage de la performance',
    'list.indicators.activeCount': 'indicateurs actifs',
    'list.indicators.dashboard': 'Dashboard',
    'list.indicators.new': 'Nouvel indicateur',
    'list.indicators.searchPlaceholder': 'Rechercher par nom ou code...',
    'list.indicators.target': 'Cible',
    'list.indicators.latest': 'Dernier',
    'list.indicators.alert': '⚠ Alerte',
    'list.indicators.compliant': '✓ Conforme',
    'list.indicators.ok': '✓ OK',
    'list.indicators.enterValues': 'Saisir valeurs',
    'list.indicators.indicator': 'Indicateur',
    'list.indicators.targetThreshold': 'Cible / Seuil',
    'list.indicators.latestReading': 'Dernier releve',
    'list.indicators.emptyTitle': 'Aucun indicateur trouve',
    'list.indicators.emptyText': 'Ajustez vos filtres ou creez un nouvel indicateur.',
    'list.documents.title': 'Documents',
    'list.documents.subtitle': 'Gestion du referentiel documentaire et des revisions',
    'list.documents.import': 'Importer',
    'list.documents.new': 'Nouveau document',
    'list.documents.quickSearch': 'Recherche rapide',
    'list.documents.searchPlaceholder': 'Code, titre ou processus...',
    'list.documents.docType': 'Type de document',
    'list.documents.manuals': 'Manuels',
    'list.documents.records': 'Enregistrements',
    'list.documents.forms': 'Formulaires',
    'list.documents.approved': 'Approuves',
    'list.documents.inReview': 'En revision',
    'list.documents.rejected': 'Rejetes',
    'list.documents.expired': 'Perimes',
    'list.documents.totalDocuments': 'Total Documents',
    'list.documents.activeFiles': 'Fichiers actifs',
    'list.documents.readyToUse': "Prets a l'emploi",
    'list.documents.updatesInProgress': 'Mises a jour en cours',
    'list.documents.needAction': 'Necessitent une action',
    'list.documents.loading': 'Traitement des documents...',
    'list.documents.emptyTitle': 'Aucun document trouve',
    'list.documents.emptyText': 'Ajuste les filtres ou televerse un nouveau fichier.',
    'list.documents.designation': 'Designation',
    'list.documents.nature': 'Nature',
    'list.documents.revision': 'Rev.',
    'list.documents.lastUpdate': 'Derniere maj',
    'common.back': 'Retour',
    'common.backToList': 'Retour a la liste',
    'common.cancel': 'Annuler',
    'common.download': 'Telecharger',
    'common.formCompletion': 'Progression du formulaire',
    'common.initializing': 'Initialisation...',
    'common.loadingForm': 'Chargement du formulaire...',
    'common.requiredHint': 'Les champs * sont obligatoires',
    'common.save': 'Enregistrer',
    'detail.document.loading': 'Chargement du document...',
    'detail.document.versions': 'Versions',
    'detail.procedure.loading': 'Chargement de la procedure...',
    'detail.process.loading': 'Chargement du processus...',
    'detail.process.subtitle': 'Vue detaillee du processus et de ses liaisons',
    'form.document.create': 'Creer le document',
    'form.document.editTitle': 'Modifier le document',
    'form.document.newTitle': 'Nouveau document',
    'form.document.saveChanges': 'Enregistrer les modifications',
    'form.indicator.create': "Creer l'indicateur",
    'form.indicator.editTitle': "Modifier l'indicateur",
    'form.indicator.newTitle': 'Nouvel indicateur',
    'form.indicator.subtitle': 'Definissez la fiche de pilotage',
    'form.nc.editTitle': 'Modifier la non-conformite',
    'form.nc.newTitle': 'Nouvelle non-conformite',
    'form.nc.submit': 'Enregistrer la fiche',
    'form.nc.update': 'Mettre a jour la fiche',
    'form.procedure.create': 'Creer la procedure',
    'form.procedure.editTitle': 'Modifier la procedure',
    'form.procedure.newTitle': 'Nouvelle procedure',
    'form.process.create': 'Creer le processus',
    'form.process.editTitle': 'Modifier le processus',
    'form.process.newTitle': 'Nouveau processus',
    'detail.indicator.activate': 'Activer',
    'detail.indicator.actual': 'Reel',
    'detail.indicator.alertState': "Etat d'alerte",
    'detail.indicator.calcMethod': 'Methode de calcul',
    'detail.indicator.chart': 'Graphique',
    'detail.indicator.deactivate': 'Desactiver',
    'detail.indicator.description': 'Description',
    'detail.indicator.frequency': 'Frequence',
    'detail.indicator.generalInfo': 'Informations generales',
    'detail.indicator.history': 'Historique',
    'detail.indicator.loading': "Chargement de l'indicateur...",
    'detail.indicator.measure': 'Mesure',
    'detail.indicator.noAlerts': 'Aucune alerte enregistree',
    'detail.indicator.noDescription': 'Aucune description disponible.',
    'detail.indicator.notEnoughData': 'Donnees insuffisantes',
    'detail.indicator.overview': 'Synthese',
    'detail.indicator.performanceTrend': 'Evolution de la performance',
    'detail.indicator.recentAlerts': 'Alertes recentes',
    'detail.indicator.target': 'Cible',
    'detail.indicator.targetObjective': 'Objectif cible',
    'detail.indicator.unit': 'Unite de mesure',
    'detail.nc.actionPlan': "Plan d'actions",
    'detail.nc.actionTitle': "Titre de l'action",
    'detail.nc.add': 'Ajouter',
    'detail.nc.changeStatus': 'Changer le statut',
    'detail.nc.choose': 'Choisir...',
    'detail.nc.closed': 'Cloturee',
    'detail.nc.currentStatus': 'Statut actuel',
    'detail.nc.detectedDate': 'Date de detection',
    'detail.nc.deviationDescription': "Description de l'ecart",
    'detail.nc.dueDate': 'Echeance',
    'detail.nc.infoOrigin': 'Informations & origine',
    'detail.nc.inProgress': 'En cours',
    'detail.nc.linkedProcedure': 'Procedure liee',
    'detail.nc.linkedProcess': 'Processus lie',
    'detail.nc.loading': 'Chargement de la fiche...',
    'detail.nc.newAction': 'Nouvelle action',
    'detail.nc.noCorrectiveAction': 'Aucune action corrective definie.',
    'detail.nc.noDescription': 'Aucune description fournie.',
    'detail.nc.noLinkedProcedure': 'Aucune procedure liee',
    'detail.nc.noLinkedProcess': 'Aucun processus lie',
    'detail.nc.open': 'Ouverte',
    'detail.nc.typeCategory': 'Type / Categorie',
    'form.indicator.alertThreshold': "Seuil d'alerte",
    'form.indicator.calcMethod': 'Methode de calcul',
    'form.indicator.calcPlaceholder': 'Ex: (Points obtenus / Points max) * 100',
    'form.indicator.codeRef': 'Code / Reference',
    'form.indicator.descObjective': 'Description & objectif',
    'form.indicator.descPlaceholder': 'A quoi sert cet indicateur ?',
    'form.indicator.designation': "Designation de l'indicateur",
    'form.indicator.disabledDraft': 'Desactive / Brouillon',
    'form.indicator.followUpOwner': 'Responsable du suivi',
    'form.indicator.generalInfo': 'Informations generales',
    'form.indicator.initialStatus': 'Statut initial',
    'form.indicator.measureFrequency': 'Frequence de mesure',
    'form.indicator.namePlaceholder': 'Ex: Taux de satisfaction client',
    'form.indicator.operational': 'Operationnel',
    'form.indicator.pilotObjectives': 'Pilotage & objectifs',
    'form.indicator.processOwner': 'Processus responsable',
    'form.indicator.select': 'Selectionner',
    'form.indicator.targetValue': 'Valeur cible',
    'form.indicator.unit': 'Unite de mesure',
    'form.indicator.unitPlaceholder': '%, kg, etc.',
    'detail.document.activeVersion': 'Version active',
    'detail.document.author': 'Auteur',
    'detail.document.date': 'Date',
    'detail.document.descriptionContext': 'Description & contexte',
    'detail.document.downloadVersion': 'Telecharger cette version',
    'detail.document.identifier': 'Identifiant',
    'detail.document.keywords': 'Mots-cles',
    'detail.document.noCategory': 'Sans categorie',
    'detail.document.noDescription': 'Aucune description fournie.',
    'detail.document.noKeyword': 'Aucun mot-cle',
    'detail.document.noProcedureLinked': 'Aucune procedure liee',
    'detail.document.noProcessLinked': 'Aucun processus lie',
    'detail.document.noVersionHistory': 'Aucun historique de version',
    'detail.document.previewActiveVersion': 'Previsualiser la version active',
    'detail.document.procedureLink': 'Procedure liee',
    'detail.document.processLink': 'Liaison processus',
    'detail.document.summaryNotes': 'Resume / Notes',
    'detail.document.system': 'Systeme',
    'detail.document.typeNature': 'Type & nature',
    'detail.document.uniqueRefCode': 'Code reference unique',
    'detail.document.versionHistory': 'Historique des versions',
    'detail.procedure.instruction': 'Instruction',
    'detail.procedure.instructions': 'Instructions',
    'detail.procedure.instructionTitle': "Titre de l'instruction",
    'detail.procedure.lastUpdated': 'Derniere mise a jour',
    'detail.procedure.never': 'Jamais',
    'detail.procedure.noInstruction': 'Aucune instruction associee.',
    'detail.procedure.notProvided': 'Non renseigne.',
    'detail.procedure.order': 'Ordre',
    'detail.procedure.parentProcess': 'Processus parent',
    'detail.process.actorType': "Type d'acteur",
    'detail.process.addActor': 'Ajouter un acteur',
    'detail.process.all': 'TOUTES',
    'detail.process.assignedAt': 'Assigne le',
    'detail.process.clients': 'Clients',
    'detail.process.documentsCount': 'document(s)',
    'detail.process.email': 'Email',
    'detail.process.finalities': 'Finalites',
    'detail.process.flowsData': 'Flux & donnees',
    'detail.process.function': 'Fonction',
    'detail.process.inputData': "Donnees d'entree",
    'detail.process.linkedMapping': 'Cartographie liee',
    'detail.process.name': 'Nom',
    'detail.process.noActor': 'Aucun acteur assigne.',
    'detail.process.noLinkedDocument': 'Aucun document lie a cette selection.',
    'detail.process.noProcedureLink': 'Aucun lien procedure disponible pour ce processus.',
    'detail.process.outputData': 'Donnees de sortie',
    'detail.process.proceduresCount': 'procedure(s)',
    'detail.process.processActors': 'Acteurs du processus',
    'detail.process.processDocuments': 'Documents du processus',
    'detail.process.removeActor': "Retirer l'acteur",
    'detail.process.suppliers': 'Fournisseurs',
    'detail.process.user': 'Utilisateur',
    'form.nc.categoryType': 'Categorie / Type',
    'form.nc.codeHint': 'Format suggere: NC-YYYY-XXX',
    'form.nc.codeRequired': 'Code obligatoire',
    'form.nc.concernedProcedure': 'Procedure concernee',
    'form.nc.contextAssignment': 'Contexte & affectation',
    'form.nc.contextAssignmentDesc': "Liez l'ecart a un element metier et designez un responsable.",
    'form.nc.descriptionPlaceholder': 'Expliquez ici les faits constates et les preuves.',
    'form.nc.detailedDescription': 'Description detaillee',
    'form.nc.detectedDate': 'Date de detection',
    'form.nc.identification': "Identification de l'ecart",
    'form.nc.identificationCode': 'Code identification',
    'form.nc.identificationDesc': "Definissez l'origine et la nature de la non-conformite.",
    'form.nc.impactedProcess': 'Processus impacte',
    'form.nc.initialStatus': 'Statut initial',
    'form.nc.none': '-- Aucun --',
    'form.nc.ownerRequired': 'Veuillez designer un responsable',
    'form.nc.processingOwner': 'Responsable du traitement',
    'form.nc.qualification': 'Qualification',
    'form.nc.selectPilot': 'Selectionner un pilote...',
    'form.nc.severityImpact': 'Severite / impact',
    'form.nc.titleLabel': 'Titre de la non-conformite',
    'form.nc.titlePlaceholder': "Description courte de l'ecart",
    'form.nc.titleRequired': 'Un titre explicite est requis',
    'form.nc.validation': 'Validation',
    'form.procedure.codeError': 'Code requis (format valide).',
    'form.procedure.detailedDescription': 'Description detaillee',
    'form.procedure.identificationParent': 'Identification & parent',
    'form.procedure.identificationParentDesc': "Definis le code unique et le processus d'appartenance.",
    'form.procedure.mainObjective': 'Objectif principal',
    'form.procedure.none': 'Aucun',
    'form.procedure.objectivesScope': 'Objectifs & perimetre',
    'form.procedure.objectivesScopeDesc': "Detaille le but et le champ d'application de cette procedure.",
    'form.procedure.parentProcess': 'Processus parent',
    'form.procedure.responsibilityStatus': 'Responsabilite & statut',
    'form.procedure.responsibilityStatusDesc': "Assigne un pilote et definit l'etat operationnel.",
    'form.procedure.scope': 'Perimetre (Scope)',
    'form.procedure.selectionRequired': 'Selection obligatoire.',
    'form.procedure.titleError': 'Titre requis (min 3 car.).',
    'form.procedure.titleLabel': 'Titre de la procedure',
    'form.procedure.titlePlaceholder': 'Ex: Gestion des non-conformites',
    'form.process.codeError': 'Code requis (format A-Z, 0-9)',
    'form.process.descriptionScope': 'Description ou perimetre resume',
    'form.process.generalInfo': 'Informations generales',
    'form.process.generalInfoDesc': 'Identite du processus et responsabilites.',
    'form.process.mappingInterfaces': 'Cartographie & interfaces',
    'form.process.mappingInterfacesDesc': "Flux d'entree, sortie et parties prenantes.",
    'form.process.name': 'Nom du processus',
    'form.process.nameError': 'Nom requis (min 3 car.)',
    'form.process.namePlaceholder': 'Management de la qualite',
    'form.process.pilotOwner': 'Pilote responsable',
    'form.process.pilotPerformance': 'Pilotage & performance',
    'form.process.pilotPerformanceDesc': 'Finalites et objectifs cibles.'
  },
  en: {
    'settings.title': 'Settings',
    'settings.subtitle': 'Customize your QualiFlow experience and manage your preferences.',
    'settings.appearance': 'Appearance',
    'settings.darkMode': 'Dark mode',
    'settings.darkModeDesc': 'Switch to a calmer visual interface for your eyes.',
    'settings.language': 'Interface language',
    'settings.preferredLanguage': 'Preferred language',
    'settings.preferredLanguageDesc': 'Choose the language used for menus and system messages.',
    'settings.selectLanguage': 'Select a language',
    'settings.about': 'Platform information',
    'settings.aboutText': 'QualiFlow is an advanced quality management suite. It centralizes process governance, document control, and non-conformity management to support continuous improvement.',
    'settings.documentation': 'Documentation',
    'settings.support': 'Technical support',
    'sidebar.general': 'General',
    'sidebar.home': 'Home',
    'sidebar.notifications': 'Notifications',
    'sidebar.chatbot': 'GED Assistant',
    'sidebar.qualityManagement': 'Quality management',
    'sidebar.processes': 'Processes',
    'sidebar.mapping': 'Mapping',
    'sidebar.procedures': 'Procedures',
    'sidebar.nonConformities': 'Non-conformities',
    'sidebar.correctiveActions': 'Corrective actions',
    'sidebar.kpiIndicators': 'KPI indicators',
    'sidebar.documents': 'Documents',
    'sidebar.departments': 'Departments',
    'sidebar.orgAdmin': 'Org administration',
    'sidebar.myOrganization': 'My organization',
    'sidebar.usersRoles': 'Users and roles',
    'sidebar.account': 'Account',
    'sidebar.profile': 'Profile',
    'sidebar.settings': 'Settings',
    'sidebar.organizations': 'Institutes / Organizations',
    'common.search': 'Search',
    'common.type': 'Type',
    'common.status': 'Status',
    'common.severity': 'Severity',
    'common.filter': 'Filter',
    'common.reset': 'Reset',
    'common.code': 'Code',
    'common.title': 'Title',
    'common.createdAt': 'Created',
    'common.responsible': 'Owner',
    'common.toDefine': 'To define',
    'common.actions': 'Actions',
    'common.details': 'Details',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.refresh': 'Refresh',
    'common.allTypes': 'All types',
    'common.allStatuses': 'All statuses',
    'common.allSeverities': 'All severities',
    'list.processes.title': 'Processes',
    'list.processes.mapping': 'Mapping',
    'list.processes.activeCount': 'active processes',
    'list.processes.new': 'New process',
    'list.processes.searchPlaceholder': 'Code, name or description',
    'list.processes.pilot': 'Pilot',
    'list.processes.allPilots': 'All pilots',
    'list.processes.loading': 'Loading processes...',
    'list.processes.emptyTitle': 'No processes found',
    'list.processes.emptyText': 'Adjust filters or create a new process.',
    'list.processes.performance': 'Performance',
    'list.procedures.title': 'Procedures',
    'list.procedures.activeCount': 'active procedures in repository',
    'list.procedures.new': 'New procedure',
    'list.procedures.searchPlaceholder': 'Code, title or description',
    'list.procedures.allProcesses': 'All processes',
    'list.procedures.allResponsibles': 'All owners',
    'list.procedures.loading': 'Loading procedures...',
    'list.procedures.emptyTitle': 'No procedures found',
    'list.procedures.emptyText': 'Adjust filters or create a procedure.',
    'list.nonconformities.title': 'Non-conformities',
    'list.nonconformities.subtitle': 'Quality deviations and corrective treatment tracking',
    'list.nonconformities.new': 'New record',
    'list.nonconformities.searchPlaceholder': 'Code, title or description',
    'list.nonconformities.totalManaged': 'Total managed',
    'list.nonconformities.records': 'Recorded files',
    'list.nonconformities.openInProgress': 'Open / In progress',
    'list.nonconformities.opened': 'open',
    'list.nonconformities.inProgress': 'in progress',
    'list.nonconformities.critical': 'Critical',
    'list.nonconformities.criticalHelp': 'Immediate action required',
    'list.nonconformities.overdueActions': 'Overdue actions',
    'list.nonconformities.deadlinesExceeded': 'Deadlines exceeded',
    'list.nonconformities.loading': 'Analyzing data...',
    'list.nonconformities.emptyTitle': 'No non-conformities',
    'list.nonconformities.emptyText': 'Adjust filters or create a new record.',
    'list.nonconformities.titleDesc': 'Title & Description',
    'list.nonconformities.state': 'State',
    'list.nonconformities.linkedTo': 'Links',
    'list.nonconformities.detected': 'Detected',
    'list.indicators.title': 'KPI Indicators',
    'list.indicators.subtitle': 'Performance monitoring',
    'list.indicators.activeCount': 'active indicators',
    'list.indicators.dashboard': 'Dashboard',
    'list.indicators.new': 'New indicator',
    'list.indicators.searchPlaceholder': 'Search by name or code...',
    'list.indicators.target': 'Target',
    'list.indicators.latest': 'Latest',
    'list.indicators.alert': '⚠ Alert',
    'list.indicators.compliant': '✓ Compliant',
    'list.indicators.ok': '✓ OK',
    'list.indicators.enterValues': 'Enter values',
    'list.indicators.indicator': 'Indicator',
    'list.indicators.targetThreshold': 'Target / Threshold',
    'list.indicators.latestReading': 'Latest reading',
    'list.indicators.emptyTitle': 'No indicators found',
    'list.indicators.emptyText': 'Adjust filters or create a new indicator.',
    'list.documents.title': 'Documents',
    'list.documents.subtitle': 'Document repository and revision management',
    'list.documents.import': 'Import',
    'list.documents.new': 'New document',
    'list.documents.quickSearch': 'Quick search',
    'list.documents.searchPlaceholder': 'Code, title or process...',
    'list.documents.docType': 'Document type',
    'list.documents.manuals': 'Manuals',
    'list.documents.records': 'Records',
    'list.documents.forms': 'Forms',
    'list.documents.approved': 'Approved',
    'list.documents.inReview': 'In review',
    'list.documents.rejected': 'Rejected',
    'list.documents.expired': 'Expired',
    'list.documents.totalDocuments': 'Total documents',
    'list.documents.activeFiles': 'Active files',
    'list.documents.readyToUse': 'Ready to use',
    'list.documents.updatesInProgress': 'Updates in progress',
    'list.documents.needAction': 'Need action',
    'list.documents.loading': 'Processing documents...',
    'list.documents.emptyTitle': 'No documents found',
    'list.documents.emptyText': 'Adjust filters or upload a new file.',
    'list.documents.designation': 'Designation',
    'list.documents.nature': 'Nature',
    'list.documents.revision': 'Rev.',
    'list.documents.lastUpdate': 'Last update',
    'common.back': 'Back',
    'common.backToList': 'Back to list',
    'common.cancel': 'Cancel',
    'common.download': 'Download',
    'common.formCompletion': 'Form completion',
    'common.initializing': 'Initializing...',
    'common.loadingForm': 'Loading form...',
    'common.requiredHint': 'Fields marked * are required',
    'common.save': 'Save',
    'detail.document.loading': 'Loading document...',
    'detail.document.versions': 'Versions',
    'detail.procedure.loading': 'Loading procedure...',
    'detail.process.loading': 'Loading process...',
    'detail.process.subtitle': 'Detailed process view and links',
    'form.document.create': 'Create document',
    'form.document.editTitle': 'Edit document',
    'form.document.newTitle': 'New document',
    'form.document.saveChanges': 'Save changes',
    'form.indicator.create': 'Create indicator',
    'form.indicator.editTitle': 'Edit indicator',
    'form.indicator.newTitle': 'New indicator',
    'form.indicator.subtitle': 'Define the monitoring record',
    'form.nc.editTitle': 'Edit non-conformity',
    'form.nc.newTitle': 'New non-conformity',
    'form.nc.submit': 'Save record',
    'form.nc.update': 'Update record',
    'form.procedure.create': 'Create procedure',
    'form.procedure.editTitle': 'Edit procedure',
    'form.procedure.newTitle': 'New procedure',
    'form.process.create': 'Create process',
    'form.process.editTitle': 'Edit process',
    'form.process.newTitle': 'New process',
    'detail.indicator.activate': 'Activate',
    'detail.indicator.actual': 'Actual',
    'detail.indicator.alertState': 'Alert state',
    'detail.indicator.calcMethod': 'Calculation method',
    'detail.indicator.chart': 'Chart',
    'detail.indicator.deactivate': 'Deactivate',
    'detail.indicator.description': 'Description',
    'detail.indicator.frequency': 'Frequency',
    'detail.indicator.generalInfo': 'General information',
    'detail.indicator.history': 'History',
    'detail.indicator.loading': 'Loading indicator...',
    'detail.indicator.measure': 'Measure',
    'detail.indicator.noAlerts': 'No alerts recorded',
    'detail.indicator.noDescription': 'No description available.',
    'detail.indicator.notEnoughData': 'Not enough data',
    'detail.indicator.overview': 'Overview',
    'detail.indicator.performanceTrend': 'Performance trend',
    'detail.indicator.recentAlerts': 'Recent alerts',
    'detail.indicator.target': 'Target',
    'detail.indicator.targetObjective': 'Target objective',
    'detail.indicator.unit': 'Unit',
    'detail.nc.actionPlan': 'Action plan',
    'detail.nc.actionTitle': 'Action title',
    'detail.nc.add': 'Add',
    'detail.nc.changeStatus': 'Change status',
    'detail.nc.choose': 'Choose...',
    'detail.nc.closed': 'Closed',
    'detail.nc.currentStatus': 'Current status',
    'detail.nc.detectedDate': 'Detection date',
    'detail.nc.deviationDescription': 'Deviation description',
    'detail.nc.dueDate': 'Due date',
    'detail.nc.infoOrigin': 'Information & origin',
    'detail.nc.inProgress': 'In progress',
    'detail.nc.linkedProcedure': 'Linked procedure',
    'detail.nc.linkedProcess': 'Linked process',
    'detail.nc.loading': 'Loading record...',
    'detail.nc.newAction': 'New action',
    'detail.nc.noCorrectiveAction': 'No corrective action defined.',
    'detail.nc.noDescription': 'No description provided.',
    'detail.nc.noLinkedProcedure': 'No linked procedure',
    'detail.nc.noLinkedProcess': 'No linked process',
    'detail.nc.open': 'Open',
    'detail.nc.typeCategory': 'Type / Category',
    'form.indicator.alertThreshold': 'Alert threshold',
    'form.indicator.calcMethod': 'Calculation method',
    'form.indicator.calcPlaceholder': 'Ex: (Points scored / Max points) * 100',
    'form.indicator.codeRef': 'Code / Reference',
    'form.indicator.descObjective': 'Description & objective',
    'form.indicator.descPlaceholder': 'What is this indicator used for?',
    'form.indicator.designation': 'Indicator designation',
    'form.indicator.disabledDraft': 'Disabled / Draft',
    'form.indicator.followUpOwner': 'Follow-up owner',
    'form.indicator.generalInfo': 'General information',
    'form.indicator.initialStatus': 'Initial status',
    'form.indicator.measureFrequency': 'Measurement frequency',
    'form.indicator.namePlaceholder': 'Ex: Customer satisfaction rate',
    'form.indicator.operational': 'Operational',
    'form.indicator.pilotObjectives': 'Steering & objectives',
    'form.indicator.processOwner': 'Responsible process',
    'form.indicator.select': 'Select',
    'form.indicator.targetValue': 'Target value',
    'form.indicator.unit': 'Unit',
    'form.indicator.unitPlaceholder': '%, kg, etc.',
    'detail.document.activeVersion': 'Active version',
    'detail.document.author': 'Author',
    'detail.document.date': 'Date',
    'detail.document.descriptionContext': 'Description & context',
    'detail.document.downloadVersion': 'Download this version',
    'detail.document.identifier': 'Identifier',
    'detail.document.keywords': 'Keywords',
    'detail.document.noCategory': 'No category',
    'detail.document.noDescription': 'No description provided.',
    'detail.document.noKeyword': 'No keyword',
    'detail.document.noProcedureLinked': 'No linked procedure',
    'detail.document.noProcessLinked': 'No linked process',
    'detail.document.noVersionHistory': 'No version history',
    'detail.document.previewActiveVersion': 'Preview active version',
    'detail.document.procedureLink': 'Procedure link',
    'detail.document.processLink': 'Process link',
    'detail.document.summaryNotes': 'Summary / Notes',
    'detail.document.system': 'System',
    'detail.document.typeNature': 'Type & nature',
    'detail.document.uniqueRefCode': 'Unique reference code',
    'detail.document.versionHistory': 'Version history',
    'detail.procedure.instruction': 'Instruction',
    'detail.procedure.instructions': 'Instructions',
    'detail.procedure.instructionTitle': 'Instruction title',
    'detail.procedure.lastUpdated': 'Last updated',
    'detail.procedure.never': 'Never',
    'detail.procedure.noInstruction': 'No instruction linked.',
    'detail.procedure.notProvided': 'Not provided.',
    'detail.procedure.order': 'Order',
    'detail.procedure.parentProcess': 'Parent process',
    'detail.process.actorType': 'Actor type',
    'detail.process.addActor': 'Add actor',
    'detail.process.all': 'ALL',
    'detail.process.assignedAt': 'Assigned on',
    'detail.process.clients': 'Clients',
    'detail.process.documentsCount': 'document(s)',
    'detail.process.email': 'Email',
    'detail.process.finalities': 'Purposes',
    'detail.process.flowsData': 'Flows & data',
    'detail.process.function': 'Role',
    'detail.process.inputData': 'Input data',
    'detail.process.linkedMapping': 'Linked mapping',
    'detail.process.name': 'Name',
    'detail.process.noActor': 'No actor assigned.',
    'detail.process.noLinkedDocument': 'No document linked to this selection.',
    'detail.process.noProcedureLink': 'No procedure link available for this process.',
    'detail.process.outputData': 'Output data',
    'detail.process.proceduresCount': 'procedure(s)',
    'detail.process.processActors': 'Process actors',
    'detail.process.processDocuments': 'Process documents',
    'detail.process.removeActor': 'Remove actor',
    'detail.process.suppliers': 'Suppliers',
    'detail.process.user': 'User',
    'form.nc.categoryType': 'Category / Type',
    'form.nc.codeHint': 'Suggested format: NC-YYYY-XXX',
    'form.nc.codeRequired': 'Code is required',
    'form.nc.concernedProcedure': 'Concerned procedure',
    'form.nc.contextAssignment': 'Context & assignment',
    'form.nc.contextAssignmentDesc': 'Link the deviation to a business item and assign an owner.',
    'form.nc.descriptionPlaceholder': 'Describe facts and evidence here.',
    'form.nc.detailedDescription': 'Detailed description',
    'form.nc.detectedDate': 'Detection date',
    'form.nc.identification': 'Deviation identification',
    'form.nc.identificationCode': 'Identification code',
    'form.nc.identificationDesc': 'Define the origin and nature of the non-conformity.',
    'form.nc.impactedProcess': 'Impacted process',
    'form.nc.initialStatus': 'Initial status',
    'form.nc.none': '-- None --',
    'form.nc.ownerRequired': 'Please assign an owner',
    'form.nc.processingOwner': 'Processing owner',
    'form.nc.qualification': 'Qualification',
    'form.nc.selectPilot': 'Select an owner...',
    'form.nc.severityImpact': 'Severity / impact',
    'form.nc.titleLabel': 'Non-conformity title',
    'form.nc.titlePlaceholder': 'Short deviation description',
    'form.nc.titleRequired': 'A clear title is required',
    'form.nc.validation': 'Validation',
    'form.procedure.codeError': 'Code is required (valid format).',
    'form.procedure.detailedDescription': 'Detailed description',
    'form.procedure.identificationParent': 'Identification & parent',
    'form.procedure.identificationParentDesc': 'Define unique code and parent process.',
    'form.procedure.mainObjective': 'Main objective',
    'form.procedure.none': 'None',
    'form.procedure.objectivesScope': 'Objectives & scope',
    'form.procedure.objectivesScopeDesc': 'Describe purpose and scope of this procedure.',
    'form.procedure.parentProcess': 'Parent process',
    'form.procedure.responsibilityStatus': 'Responsibility & status',
    'form.procedure.responsibilityStatusDesc': 'Assign an owner and operational status.',
    'form.procedure.scope': 'Scope',
    'form.procedure.selectionRequired': 'Selection is required.',
    'form.procedure.titleError': 'Title is required (min 3 chars).',
    'form.procedure.titleLabel': 'Procedure title',
    'form.procedure.titlePlaceholder': 'Ex: Non-conformity management',
    'form.process.codeError': 'Code is required (A-Z, 0-9)',
    'form.process.descriptionScope': 'Description or scope summary',
    'form.process.generalInfo': 'General information',
    'form.process.generalInfoDesc': 'Process identity and responsibilities.',
    'form.process.mappingInterfaces': 'Mapping & interfaces',
    'form.process.mappingInterfacesDesc': 'Input/output flows and stakeholders.',
    'form.process.name': 'Process name',
    'form.process.nameError': 'Name is required (min 3 chars)',
    'form.process.namePlaceholder': 'Quality management',
    'form.process.pilotOwner': 'Pilot owner',
    'form.process.pilotPerformance': 'Steering & performance',
    'form.process.pilotPerformanceDesc': 'Purposes and target objectives.'
  },
  ar: {
    'settings.title': 'الاعدادات',
    'settings.subtitle': 'خصص تجربتك في QualiFlow وادِر تفضيلاتك.',
    'settings.appearance': 'المظهر',
    'settings.darkMode': 'الوضع الداكن',
    'settings.darkModeDesc': 'التبديل الى واجهة مريحة للعين.',
    'settings.language': 'لغة الواجهة',
    'settings.preferredLanguage': 'اللغة المفضلة',
    'settings.preferredLanguageDesc': 'حدد اللغة المستخدمة في القوائم ورسائل النظام.',
    'settings.selectLanguage': 'اختر لغة',
    'settings.about': 'معلومات عن المنصة',
    'settings.aboutText': 'QualiFlow منصة متقدمة لادارة الجودة، توحد ادارة العمليات والوثائق وعدم المطابقة لدعم التحسين المستمر.',
    'settings.documentation': 'التوثيق',
    'settings.support': 'الدعم الفني',
    'sidebar.general': 'عام',
    'sidebar.home': 'الرئيسية',
    'sidebar.notifications': 'الاشعارات',
    'sidebar.chatbot': 'مساعد المنصة',
    'sidebar.qualityManagement': 'ادارة الجودة',
    'sidebar.processes': 'العمليات',
    'sidebar.mapping': 'الخريطة',
    'sidebar.procedures': 'الاجراءات',
    'sidebar.nonConformities': 'حالات عدم المطابقة',
    'sidebar.correctiveActions': 'الاجراءات التصحيحية',
    'sidebar.kpiIndicators': 'مؤشرات KPI',
    'sidebar.documents': 'الوثائق',
    'sidebar.departments': 'الاقسام',
    'sidebar.orgAdmin': 'ادارة المؤسسة',
    'sidebar.myOrganization': 'مؤسستي',
    'sidebar.usersRoles': 'المستخدمون والادوار',
    'sidebar.account': 'الحساب',
    'sidebar.profile': 'الملف الشخصي',
    'sidebar.settings': 'الاعدادات',
    'sidebar.organizations': 'المعاهد / المؤسسات',
    'common.search': 'بحث',
    'common.type': 'النوع',
    'common.status': 'الحالة',
    'common.severity': 'الشدة',
    'common.filter': 'تصفية',
    'common.reset': 'اعادة تعيين',
    'common.code': 'الرمز',
    'common.title': 'العنوان',
    'common.createdAt': 'الانشاء',
    'common.responsible': 'المسؤول',
    'common.toDefine': 'غير محدد',
    'common.actions': 'الاجراءات',
    'common.details': 'التفاصيل',
    'common.edit': 'تعديل',
    'common.delete': 'حذف',
    'common.refresh': 'تحديث',
    'common.allTypes': 'كل الانواع',
    'common.allStatuses': 'كل الحالات',
    'common.allSeverities': 'كل مستويات الشدة',
    'list.processes.title': 'العمليات',
    'list.processes.mapping': 'الخريطة',
    'list.processes.activeCount': 'عمليات نشطة',
    'list.processes.new': 'عملية جديدة',
    'list.processes.searchPlaceholder': 'الرمز او الاسم او الوصف',
    'list.processes.pilot': 'القائد',
    'list.processes.allPilots': 'كل القادة',
    'list.processes.loading': 'جار تحميل العمليات...',
    'list.processes.emptyTitle': 'لا توجد عمليات',
    'list.processes.emptyText': 'عدّل الفلاتر او انشئ عملية جديدة.',
    'list.processes.performance': 'الاداء',
    'list.procedures.title': 'الاجراءات',
    'list.procedures.activeCount': 'اجراءات نشطة',
    'list.procedures.new': 'اجراء جديد',
    'list.procedures.searchPlaceholder': 'الرمز او العنوان او الوصف',
    'list.procedures.allProcesses': 'كل العمليات',
    'list.procedures.allResponsibles': 'كل المسؤولين',
    'list.procedures.loading': 'جار تحميل الاجراءات...',
    'list.procedures.emptyTitle': 'لا توجد اجراءات',
    'list.procedures.emptyText': 'عدّل الفلاتر او انشئ اجراء.',
    'list.nonconformities.title': 'حالات عدم المطابقة',
    'list.nonconformities.subtitle': 'متابعة الانحرافات ومعالجتها التصحيحية',
    'list.nonconformities.new': 'سجل جديد',
    'list.nonconformities.searchPlaceholder': 'الرمز او العنوان او الوصف',
    'list.nonconformities.totalManaged': 'اجمالي المدار',
    'list.nonconformities.records': 'سجلات محفوظة',
    'list.nonconformities.openInProgress': 'مفتوحة / قيد المعالجة',
    'list.nonconformities.opened': 'مفتوحة',
    'list.nonconformities.inProgress': 'قيد المعالجة',
    'list.nonconformities.critical': 'حرجة',
    'list.nonconformities.criticalHelp': 'يتطلب اجراء فوريا',
    'list.nonconformities.overdueActions': 'اجراءات متاخرة',
    'list.nonconformities.deadlinesExceeded': 'تجاوزت المهل',
    'list.nonconformities.loading': 'جار تحليل البيانات...',
    'list.nonconformities.emptyTitle': 'لا توجد حالات عدم مطابقة',
    'list.nonconformities.emptyText': 'عدّل الفلاتر او انشئ سجلا جديدا.',
    'list.nonconformities.titleDesc': 'العنوان والوصف',
    'list.nonconformities.state': 'الحالة',
    'list.nonconformities.linkedTo': 'الربط',
    'list.nonconformities.detected': 'تاريخ الكشف',
    'list.indicators.title': 'مؤشرات KPI',
    'list.indicators.subtitle': 'متابعة الاداء',
    'list.indicators.activeCount': 'مؤشرات نشطة',
    'list.indicators.dashboard': 'لوحة التحكم',
    'list.indicators.new': 'مؤشر جديد',
    'list.indicators.searchPlaceholder': 'ابحث بالاسم او الرمز...',
    'list.indicators.target': 'الهدف',
    'list.indicators.latest': 'الاحدث',
    'list.indicators.alert': '⚠ تنبيه',
    'list.indicators.compliant': '✓ مطابق',
    'list.indicators.ok': '✓ جيد',
    'list.indicators.enterValues': 'ادخال القيم',
    'list.indicators.indicator': 'المؤشر',
    'list.indicators.targetThreshold': 'الهدف / الحد',
    'list.indicators.latestReading': 'اخر قراءة',
    'list.indicators.emptyTitle': 'لا توجد مؤشرات',
    'list.indicators.emptyText': 'عدّل الفلاتر او انشئ مؤشرا جديدا.',
    'list.documents.title': 'الوثائق',
    'list.documents.subtitle': 'ادارة مرجع الوثائق والمراجعات',
    'list.documents.import': 'استيراد',
    'list.documents.new': 'وثيقة جديدة',
    'list.documents.quickSearch': 'بحث سريع',
    'list.documents.searchPlaceholder': 'الرمز او العنوان او العملية...',
    'list.documents.docType': 'نوع الوثيقة',
    'list.documents.manuals': 'ادلّة',
    'list.documents.records': 'سجلات',
    'list.documents.forms': 'نماذج',
    'list.documents.approved': 'معتمدة',
    'list.documents.inReview': 'قيد المراجعة',
    'list.documents.rejected': 'مرفوضة',
    'list.documents.expired': 'منتهية',
    'list.documents.totalDocuments': 'اجمالي الوثائق',
    'list.documents.activeFiles': 'ملفات نشطة',
    'list.documents.readyToUse': 'جاهزة للاستخدام',
    'list.documents.updatesInProgress': 'تحديثات جارية',
    'list.documents.needAction': 'تحتاج اجراء',
    'list.documents.loading': 'جار معالجة الوثائق...',
    'list.documents.emptyTitle': 'لا توجد وثائق',
    'list.documents.emptyText': 'عدّل الفلاتر او ارفع ملفا جديدا.',
    'list.documents.designation': 'التسمية',
    'list.documents.nature': 'الطبيعة',
    'list.documents.revision': 'مراجعة',
    'list.documents.lastUpdate': 'اخر تحديث',
    'common.back': 'رجوع',
    'common.backToList': 'العودة الى القائمة',
    'common.cancel': 'الغاء',
    'common.download': 'تنزيل',
    'common.formCompletion': 'تقدم النموذج',
    'common.initializing': 'جار التهيئة...',
    'common.loadingForm': 'جار تحميل النموذج...',
    'common.requiredHint': 'الحقول * مطلوبة',
    'common.save': 'حفظ',
    'detail.document.loading': 'جار تحميل الوثيقة...',
    'detail.document.versions': 'الاصدارات',
    'detail.procedure.loading': 'جار تحميل الاجراء...',
    'detail.process.loading': 'جار تحميل العملية...',
    'detail.process.subtitle': 'عرض تفصيلي للعملية وروابطها',
    'form.document.create': 'انشاء الوثيقة',
    'form.document.editTitle': 'تعديل الوثيقة',
    'form.document.newTitle': 'وثيقة جديدة',
    'form.document.saveChanges': 'حفظ التغييرات',
    'form.indicator.create': 'انشاء مؤشر',
    'form.indicator.editTitle': 'تعديل المؤشر',
    'form.indicator.newTitle': 'مؤشر جديد',
    'form.indicator.subtitle': 'حدد بطاقة المتابعة',
    'form.nc.editTitle': 'تعديل عدم المطابقة',
    'form.nc.newTitle': 'عدم مطابقة جديدة',
    'form.nc.submit': 'حفظ السجل',
    'form.nc.update': 'تحديث السجل',
    'form.procedure.create': 'انشاء اجراء',
    'form.procedure.editTitle': 'تعديل الاجراء',
    'form.procedure.newTitle': 'اجراء جديد',
    'form.process.create': 'انشاء عملية',
    'form.process.editTitle': 'تعديل العملية',
    'form.process.newTitle': 'عملية جديدة',
    'detail.indicator.activate': 'تفعيل',
    'detail.indicator.actual': 'الفعلي',
    'detail.indicator.alertState': 'حالة التنبيه',
    'detail.indicator.calcMethod': 'طريقة الحساب',
    'detail.indicator.chart': 'الرسم البياني',
    'detail.indicator.deactivate': 'تعطيل',
    'detail.indicator.description': 'الوصف',
    'detail.indicator.frequency': 'التكرار',
    'detail.indicator.generalInfo': 'معلومات عامة',
    'detail.indicator.history': 'السجل',
    'detail.indicator.loading': 'جار تحميل المؤشر...',
    'detail.indicator.measure': 'القياس',
    'detail.indicator.noAlerts': 'لا توجد تنبيهات مسجلة',
    'detail.indicator.noDescription': 'لا يوجد وصف متاح.',
    'detail.indicator.notEnoughData': 'بيانات غير كافية',
    'detail.indicator.overview': 'ملخص',
    'detail.indicator.performanceTrend': 'تطور الاداء',
    'detail.indicator.recentAlerts': 'تنبيهات حديثة',
    'detail.indicator.target': 'الهدف',
    'detail.indicator.targetObjective': 'الهدف المستهدف',
    'detail.indicator.unit': 'وحدة القياس',
    'detail.nc.actionPlan': 'خطة الاجراءات',
    'detail.nc.actionTitle': 'عنوان الاجراء',
    'detail.nc.add': 'اضافة',
    'detail.nc.changeStatus': 'تغيير الحالة',
    'detail.nc.choose': 'اختر...',
    'detail.nc.closed': 'مغلقة',
    'detail.nc.currentStatus': 'الحالة الحالية',
    'detail.nc.detectedDate': 'تاريخ الكشف',
    'detail.nc.deviationDescription': 'وصف الانحراف',
    'detail.nc.dueDate': 'الاستحقاق',
    'detail.nc.infoOrigin': 'المعلومات والمصدر',
    'detail.nc.inProgress': 'قيد المعالجة',
    'detail.nc.linkedProcedure': 'الاجراء المرتبط',
    'detail.nc.linkedProcess': 'العملية المرتبطة',
    'detail.nc.loading': 'جار تحميل السجل...',
    'detail.nc.newAction': 'اجراء جديد',
    'detail.nc.noCorrectiveAction': 'لا توجد اجراءات تصحيحية.',
    'detail.nc.noDescription': 'لا يوجد وصف.',
    'detail.nc.noLinkedProcedure': 'لا يوجد اجراء مرتبط',
    'detail.nc.noLinkedProcess': 'لا توجد عملية مرتبطة',
    'detail.nc.open': 'مفتوحة',
    'detail.nc.typeCategory': 'النوع / الفئة',
    'form.indicator.alertThreshold': 'عتبة التنبيه',
    'form.indicator.calcMethod': 'طريقة الحساب',
    'form.indicator.calcPlaceholder': 'مثال: (النقاط المحققة / الحد الاقصى) * 100',
    'form.indicator.codeRef': 'الرمز / المرجع',
    'form.indicator.descObjective': 'الوصف والهدف',
    'form.indicator.descPlaceholder': 'ما الغرض من هذا المؤشر؟',
    'form.indicator.designation': 'تسمية المؤشر',
    'form.indicator.disabledDraft': 'معطل / مسودة',
    'form.indicator.followUpOwner': 'مسؤول المتابعة',
    'form.indicator.generalInfo': 'معلومات عامة',
    'form.indicator.initialStatus': 'الحالة الاولية',
    'form.indicator.measureFrequency': 'تكرار القياس',
    'form.indicator.namePlaceholder': 'مثال: معدل رضا العملاء',
    'form.indicator.operational': 'تشغيلي',
    'form.indicator.pilotObjectives': 'القيادة والاهداف',
    'form.indicator.processOwner': 'العملية المسؤولة',
    'form.indicator.select': 'اختر',
    'form.indicator.targetValue': 'القيمة المستهدفة',
    'form.indicator.unit': 'وحدة القياس',
    'form.indicator.unitPlaceholder': '%، كغ، الخ'
  }
};

@Pipe({
  name: 't',
  standalone: true,
  pure: false
})
export class TranslatePipe implements PipeTransform {
  transform(key: string): string {
    const lang = this.normalizeLanguage(localStorage.getItem('language'));
    return TRANSLATIONS[lang][key] ?? TRANSLATIONS[FALLBACK_LANG][key] ?? key;
  }

  private normalizeLanguage(value: string | null): AppLang {
    if (value === 'fr' || value === 'en' || value === 'ar') {
      return value;
    }

    return FALLBACK_LANG;
  }
}
